// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: metrics.proto

package metricspb

import (
	commonpb "github.com/honeycombio/opentelemetry-proto/compat07/internal/shadowpb/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AggregationTemporality mirrors the upstream enum with identical int values.
// Defined here to avoid a cross-package proto dependency on upstream metrics.proto.
type AggregationTemporality int32

const (
	AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED AggregationTemporality = 0
	AggregationTemporality_AGGREGATION_TEMPORALITY_DELTA       AggregationTemporality = 1
	AggregationTemporality_AGGREGATION_TEMPORALITY_CUMULATIVE  AggregationTemporality = 2
)

// Enum value maps for AggregationTemporality.
var (
	AggregationTemporality_name = map[int32]string{
		0: "AGGREGATION_TEMPORALITY_UNSPECIFIED",
		1: "AGGREGATION_TEMPORALITY_DELTA",
		2: "AGGREGATION_TEMPORALITY_CUMULATIVE",
	}
	AggregationTemporality_value = map[string]int32{
		"AGGREGATION_TEMPORALITY_UNSPECIFIED": 0,
		"AGGREGATION_TEMPORALITY_DELTA":       1,
		"AGGREGATION_TEMPORALITY_CUMULATIVE":  2,
	}
)

func (x AggregationTemporality) Enum() *AggregationTemporality {
	p := new(AggregationTemporality)
	*p = x
	return p
}

func (x AggregationTemporality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggregationTemporality) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_proto_enumTypes[0].Descriptor()
}

func (AggregationTemporality) Type() protoreflect.EnumType {
	return &file_metrics_proto_enumTypes[0]
}

func (x AggregationTemporality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AggregationTemporality.Descriptor instead.
func (AggregationTemporality) EnumDescriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

// IntExemplar is the OTLP 0.7 integer exemplar type.
// Upstream field: IntExemplar in opentelemetry.proto.metrics.v1 (lines 913-939).
type IntExemplar struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	FilteredLabels []*commonpb.StringKeyValue `protobuf:"bytes,1,rep,name=filtered_labels,json=filteredLabels,proto3" json:"filtered_labels,omitempty"`
	TimeUnixNano   uint64                     `protobuf:"fixed64,2,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Value          int64                      `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	SpanId         []byte                     `protobuf:"bytes,4,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	TraceId        []byte                     `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IntExemplar) Reset() {
	*x = IntExemplar{}
	mi := &file_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntExemplar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntExemplar) ProtoMessage() {}

func (x *IntExemplar) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntExemplar.ProtoReflect.Descriptor instead.
func (*IntExemplar) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *IntExemplar) GetFilteredLabels() []*commonpb.StringKeyValue {
	if x != nil {
		return x.FilteredLabels
	}
	return nil
}

func (x *IntExemplar) GetTimeUnixNano() uint64 {
	if x != nil {
		return x.TimeUnixNano
	}
	return 0
}

func (x *IntExemplar) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *IntExemplar) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *IntExemplar) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

// IntDataPoint is the OTLP 0.7 integer data point used by IntGauge and IntSum.
// Upstream field: IntDataPoint in opentelemetry.proto.metrics.v1 (lines 793-818).
type IntDataPoint struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	Labels            []*commonpb.StringKeyValue `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	StartTimeUnixNano uint64                     `protobuf:"fixed64,2,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	TimeUnixNano      uint64                     `protobuf:"fixed64,3,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Value             int64                      `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Exemplars         []*IntExemplar             `protobuf:"bytes,5,rep,name=exemplars,proto3" json:"exemplars,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IntDataPoint) Reset() {
	*x = IntDataPoint{}
	mi := &file_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntDataPoint) ProtoMessage() {}

func (x *IntDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntDataPoint.ProtoReflect.Descriptor instead.
func (*IntDataPoint) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *IntDataPoint) GetLabels() []*commonpb.StringKeyValue {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *IntDataPoint) GetStartTimeUnixNano() uint64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *IntDataPoint) GetTimeUnixNano() uint64 {
	if x != nil {
		return x.TimeUnixNano
	}
	return 0
}

func (x *IntDataPoint) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *IntDataPoint) GetExemplars() []*IntExemplar {
	if x != nil {
		return x.Exemplars
	}
	return nil
}

// IntGauge is the OTLP 0.7 integer gauge.
// Appears as Metric.data oneof field 4 (int_gauge) in the upstream Metric message.
type IntGauge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataPoints    []*IntDataPoint        `protobuf:"bytes,1,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntGauge) Reset() {
	*x = IntGauge{}
	mi := &file_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntGauge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntGauge) ProtoMessage() {}

func (x *IntGauge) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntGauge.ProtoReflect.Descriptor instead.
func (*IntGauge) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *IntGauge) GetDataPoints() []*IntDataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

// IntSum is the OTLP 0.7 integer sum.
// Appears as Metric.data oneof field 6 (int_sum) in the upstream Metric message.
type IntSum struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	DataPoints             []*IntDataPoint        `protobuf:"bytes,1,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	AggregationTemporality AggregationTemporality `protobuf:"varint,2,opt,name=aggregation_temporality,json=aggregationTemporality,proto3,enum=honeycomb.compat.otlp07.metrics.AggregationTemporality" json:"aggregation_temporality,omitempty"`
	IsMonotonic            bool                   `protobuf:"varint,3,opt,name=is_monotonic,json=isMonotonic,proto3" json:"is_monotonic,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IntSum) Reset() {
	*x = IntSum{}
	mi := &file_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntSum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntSum) ProtoMessage() {}

func (x *IntSum) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntSum.ProtoReflect.Descriptor instead.
func (*IntSum) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{3}
}

func (x *IntSum) GetDataPoints() []*IntDataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

func (x *IntSum) GetAggregationTemporality() AggregationTemporality {
	if x != nil {
		return x.AggregationTemporality
	}
	return AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED
}

func (x *IntSum) GetIsMonotonic() bool {
	if x != nil {
		return x.IsMonotonic
	}
	return false
}

// IntHistogramDataPoint is the OTLP 0.7 integer histogram data point.
// Upstream field: IntHistogramDataPoint in opentelemetry.proto.metrics.v1 (lines 842-898).
type IntHistogramDataPoint struct {
	state             protoimpl.MessageState     `protogen:"open.v1"`
	Labels            []*commonpb.StringKeyValue `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty"`
	StartTimeUnixNano uint64                     `protobuf:"fixed64,2,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"start_time_unix_nano,omitempty"`
	TimeUnixNano      uint64                     `protobuf:"fixed64,3,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Count             uint64                     `protobuf:"fixed64,4,opt,name=count,proto3" json:"count,omitempty"`
	Sum               int64                      `protobuf:"fixed64,5,opt,name=sum,proto3" json:"sum,omitempty"`
	BucketCounts      []uint64                   `protobuf:"fixed64,6,rep,packed,name=bucket_counts,json=bucketCounts,proto3" json:"bucket_counts,omitempty"`
	ExplicitBounds    []float64                  `protobuf:"fixed64,7,rep,packed,name=explicit_bounds,json=explicitBounds,proto3" json:"explicit_bounds,omitempty"`
	Exemplars         []*IntExemplar             `protobuf:"bytes,8,rep,name=exemplars,proto3" json:"exemplars,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IntHistogramDataPoint) Reset() {
	*x = IntHistogramDataPoint{}
	mi := &file_metrics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntHistogramDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntHistogramDataPoint) ProtoMessage() {}

func (x *IntHistogramDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntHistogramDataPoint.ProtoReflect.Descriptor instead.
func (*IntHistogramDataPoint) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{4}
}

func (x *IntHistogramDataPoint) GetLabels() []*commonpb.StringKeyValue {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *IntHistogramDataPoint) GetStartTimeUnixNano() uint64 {
	if x != nil {
		return x.StartTimeUnixNano
	}
	return 0
}

func (x *IntHistogramDataPoint) GetTimeUnixNano() uint64 {
	if x != nil {
		return x.TimeUnixNano
	}
	return 0
}

func (x *IntHistogramDataPoint) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *IntHistogramDataPoint) GetSum() int64 {
	if x != nil {
		return x.Sum
	}
	return 0
}

func (x *IntHistogramDataPoint) GetBucketCounts() []uint64 {
	if x != nil {
		return x.BucketCounts
	}
	return nil
}

func (x *IntHistogramDataPoint) GetExplicitBounds() []float64 {
	if x != nil {
		return x.ExplicitBounds
	}
	return nil
}

func (x *IntHistogramDataPoint) GetExemplars() []*IntExemplar {
	if x != nil {
		return x.Exemplars
	}
	return nil
}

// IntHistogram is the OTLP 0.7 integer histogram.
// Appears as Metric.data oneof field 8 (int_histogram) in the upstream Metric message.
type IntHistogram struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	DataPoints             []*IntHistogramDataPoint `protobuf:"bytes,1,rep,name=data_points,json=dataPoints,proto3" json:"data_points,omitempty"`
	AggregationTemporality AggregationTemporality   `protobuf:"varint,2,opt,name=aggregation_temporality,json=aggregationTemporality,proto3,enum=honeycomb.compat.otlp07.metrics.AggregationTemporality" json:"aggregation_temporality,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *IntHistogram) Reset() {
	*x = IntHistogram{}
	mi := &file_metrics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntHistogram) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntHistogram) ProtoMessage() {}

func (x *IntHistogram) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntHistogram.ProtoReflect.Descriptor instead.
func (*IntHistogram) Descriptor() ([]byte, []int) {
	return file_metrics_proto_rawDescGZIP(), []int{5}
}

func (x *IntHistogram) GetDataPoints() []*IntHistogramDataPoint {
	if x != nil {
		return x.DataPoints
	}
	return nil
}

func (x *IntHistogram) GetAggregationTemporality() AggregationTemporality {
	if x != nil {
		return x.AggregationTemporality
	}
	return AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED
}

var File_metrics_proto protoreflect.FileDescriptor

const file_metrics_proto_rawDesc = "" +
	"\n" +
	"\rmetrics.proto\x12\x1fhoneycomb.compat.otlp07.metrics\x1a\fcommon.proto\"\xd6\x01\n" +
	"\vIntExemplar\x12W\n" +
	"\x0ffiltered_labels\x18\x01 \x03(\v2..honeycomb.compat.otlp07.common.StringKeyValueR\x0efilteredLabels\x12$\n" +
	"\x0etime_unix_nano\x18\x02 \x01(\x06R\ftimeUnixNano\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x10R\x05value\x12\x17\n" +
	"\aspan_id\x18\x04 \x01(\fR\x06spanId\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\fR\atraceId\"\x8f\x02\n" +
	"\fIntDataPoint\x12F\n" +
	"\x06labels\x18\x01 \x03(\v2..honeycomb.compat.otlp07.common.StringKeyValueR\x06labels\x12/\n" +
	"\x14start_time_unix_nano\x18\x02 \x01(\x06R\x11startTimeUnixNano\x12$\n" +
	"\x0etime_unix_nano\x18\x03 \x01(\x06R\ftimeUnixNano\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x10R\x05value\x12J\n" +
	"\texemplars\x18\x05 \x03(\v2,.honeycomb.compat.otlp07.metrics.IntExemplarR\texemplars\"Z\n" +
	"\bIntGauge\x12N\n" +
	"\vdata_points\x18\x01 \x03(\v2-.honeycomb.compat.otlp07.metrics.IntDataPointR\n" +
	"dataPoints\"\xed\x01\n" +
	"\x06IntSum\x12N\n" +
	"\vdata_points\x18\x01 \x03(\v2-.honeycomb.compat.otlp07.metrics.IntDataPointR\n" +
	"dataPoints\x12p\n" +
	"\x17aggregation_temporality\x18\x02 \x01(\x0e27.honeycomb.compat.otlp07.metrics.AggregationTemporalityR\x16aggregationTemporality\x12!\n" +
	"\fis_monotonic\x18\x03 \x01(\bR\visMonotonic\"\xf8\x02\n" +
	"\x15IntHistogramDataPoint\x12F\n" +
	"\x06labels\x18\x01 \x03(\v2..honeycomb.compat.otlp07.common.StringKeyValueR\x06labels\x12/\n" +
	"\x14start_time_unix_nano\x18\x02 \x01(\x06R\x11startTimeUnixNano\x12$\n" +
	"\x0etime_unix_nano\x18\x03 \x01(\x06R\ftimeUnixNano\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x06R\x05count\x12\x10\n" +
	"\x03sum\x18\x05 \x01(\x10R\x03sum\x12#\n" +
	"\rbucket_counts\x18\x06 \x03(\x06R\fbucketCounts\x12'\n" +
	"\x0fexplicit_bounds\x18\a \x03(\x01R\x0eexplicitBounds\x12J\n" +
	"\texemplars\x18\b \x03(\v2,.honeycomb.compat.otlp07.metrics.IntExemplarR\texemplars\"\xd9\x01\n" +
	"\fIntHistogram\x12W\n" +
	"\vdata_points\x18\x01 \x03(\v26.honeycomb.compat.otlp07.metrics.IntHistogramDataPointR\n" +
	"dataPoints\x12p\n" +
	"\x17aggregation_temporality\x18\x02 \x01(\x0e27.honeycomb.compat.otlp07.metrics.AggregationTemporalityR\x16aggregationTemporality*\x8c\x01\n" +
	"\x16AggregationTemporality\x12'\n" +
	"#AGGREGATION_TEMPORALITY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dAGGREGATION_TEMPORALITY_DELTA\x10\x01\x12&\n" +
	"\"AGGREGATION_TEMPORALITY_CUMULATIVE\x10\x02B[ZYgithub.com/honeycombio/opentelemetry-proto/compat07/internal/shadowpb/metricspb;metricspbb\x06proto3"

var (
	file_metrics_proto_rawDescOnce sync.Once
	file_metrics_proto_rawDescData []byte
)

func file_metrics_proto_rawDescGZIP() []byte {
	file_metrics_proto_rawDescOnce.Do(func() {
		file_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)))
	})
	return file_metrics_proto_rawDescData
}

var file_metrics_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_metrics_proto_goTypes = []any{
	(AggregationTemporality)(0),     // 0: honeycomb.compat.otlp07.metrics.AggregationTemporality
	(*IntExemplar)(nil),             // 1: honeycomb.compat.otlp07.metrics.IntExemplar
	(*IntDataPoint)(nil),            // 2: honeycomb.compat.otlp07.metrics.IntDataPoint
	(*IntGauge)(nil),                // 3: honeycomb.compat.otlp07.metrics.IntGauge
	(*IntSum)(nil),                  // 4: honeycomb.compat.otlp07.metrics.IntSum
	(*IntHistogramDataPoint)(nil),   // 5: honeycomb.compat.otlp07.metrics.IntHistogramDataPoint
	(*IntHistogram)(nil),            // 6: honeycomb.compat.otlp07.metrics.IntHistogram
	(*commonpb.StringKeyValue)(nil), // 7: honeycomb.compat.otlp07.common.StringKeyValue
}
var file_metrics_proto_depIdxs = []int32{
	7,  // 0: honeycomb.compat.otlp07.metrics.IntExemplar.filtered_labels:type_name -> honeycomb.compat.otlp07.common.StringKeyValue
	7,  // 1: honeycomb.compat.otlp07.metrics.IntDataPoint.labels:type_name -> honeycomb.compat.otlp07.common.StringKeyValue
	1,  // 2: honeycomb.compat.otlp07.metrics.IntDataPoint.exemplars:type_name -> honeycomb.compat.otlp07.metrics.IntExemplar
	2,  // 3: honeycomb.compat.otlp07.metrics.IntGauge.data_points:type_name -> honeycomb.compat.otlp07.metrics.IntDataPoint
	2,  // 4: honeycomb.compat.otlp07.metrics.IntSum.data_points:type_name -> honeycomb.compat.otlp07.metrics.IntDataPoint
	0,  // 5: honeycomb.compat.otlp07.metrics.IntSum.aggregation_temporality:type_name -> honeycomb.compat.otlp07.metrics.AggregationTemporality
	7,  // 6: honeycomb.compat.otlp07.metrics.IntHistogramDataPoint.labels:type_name -> honeycomb.compat.otlp07.common.StringKeyValue
	1,  // 7: honeycomb.compat.otlp07.metrics.IntHistogramDataPoint.exemplars:type_name -> honeycomb.compat.otlp07.metrics.IntExemplar
	5,  // 8: honeycomb.compat.otlp07.metrics.IntHistogram.data_points:type_name -> honeycomb.compat.otlp07.metrics.IntHistogramDataPoint
	0,  // 9: honeycomb.compat.otlp07.metrics.IntHistogram.aggregation_temporality:type_name -> honeycomb.compat.otlp07.metrics.AggregationTemporality
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_metrics_proto_init() }
func file_metrics_proto_init() {
	if File_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_proto_rawDesc), len(file_metrics_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_proto_goTypes,
		DependencyIndexes: file_metrics_proto_depIdxs,
		EnumInfos:         file_metrics_proto_enumTypes,
		MessageInfos:      file_metrics_proto_msgTypes,
	}.Build()
	File_metrics_proto = out.File
	file_metrics_proto_goTypes = nil
	file_metrics_proto_depIdxs = nil
}
